# Run CI for R using https://eddelbuettel.github.io/r-ci/

language: c
sudo: required
dist: focal

jobs:
  include:
    - name: linux
      os: linux

env:
  global:
    - NOT_CRAN="true"

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - Rscript -e "utils::download.file('https://api.github.com/repos/jranke/chents/contents/DESCRIPTION?ref=HEAD', destfile = 'tmp.json')"
  - ./run.sh install_deps

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

after_success:
  - travis_wait ./run.sh coverage

notifications:
  email:
    on_success: change
    on_failure: change
